### ISSUE TITLE
[CI] Ubuntu 1604 package repository has been dropped

### ISSUE THREAD

**Issue by sticky-note** [myii/ssf-formula#329]
See https://packages.ubuntu.com/ 's `News` heading

**Comment by myii** [comment]
@sticky-note Yes, thanks for this reminder.  As I mentioned in the [previous working group meeting](https://youtu.be/DfHfwF32v5k?t=1243), I was planning to tackle the removals of both Ubuntu 16.04 and Fedora 32 when we update the CI after the upcoming 3003.1 release.  Since that's been delayed a bit, these removals have also been held up.
